### PR TITLE
Make loading of external resources protocol agnostic to prevent mixed content warnings

### PR DESCRIPTION
**Pull request by zeidlos**
We are using your tool, but would love to be able to also serve it via https. This should fix it. :)

### CODE REVIEW

**Comment by zeidlos** [comment]
Fixes https://github.com/SassDoc/sassdoc-theme-default/issues/91

**Comment by valeriangalliat** [comment]
Thanks!

Realizing that this resource is available over HTTPS, I think it's even better to **always** load it over HTTPS. Could you update the PR?

**Comment by pascalduez** [comment]
Protocol-relative URLs are deprecated and considered potentially harmful. See http://www.paulirish.com/2010/the-protocol-relative-url/.

So I would rather go with HTTPS as @valeriangalliat suggested.

**Comment by zeidlos** [comment]
Updated it. I'd be happy if you guys could merge soon, so I gtd. :)

**Comment by pascalduez** [comment]
:+1:

**Comment by zeidlos** [comment]
Will you change the version number as well?

**Comment by pascalduez** [comment]
`sassdoc-theme-default@2.4.3` published.

**Pull request merged**
