### PR TITLE
Add colour variable preview support. Fixes #28.

### LINKED ISSUE #28: Ability to output a color value from a variable
It would be nice if the sassdoc detected that a color is being used as a value of a variable. It should then output a tile with the configured color.

    /**
     * The theme color used for creating a color range.
     * @type color
     */
    $theme-color: rgb(85,128,182) !default;

### PR DESCRIPTION
**Pull request by ben-eb**
screen shot 2014-12-31 at 15 04 14

Not sure if there's a more elegant way to do this in swig. I'd prefer some logic that is like this in JS:

```js
if (~item.type.indexOf('color')) {
    // => print the colour
}
```

Anyway, thought I'd fix this for you. :smile:

### CODE REVIEW

**Comment by ben-eb** [comment]
Updated with the colour value inline.

screen shot 2015-01-01 at 12 26 03

**Comment by valeriangalliat** [comment]
What do you think when inverting the text and background colors?

Inverted text and background colors

I believe it gives a better visibility to the *actual* color.

**Comment by valeriangalliat** [comment]
BTW we'll need to merge this manually into `develop` at the end, since GitHub still won't allow us to change the target branch of a PR.

**Comment by ben-eb** [comment]
@valeriangalliat Can just close this one, rebase and make a new PR into develop once we're happy? Yeah I think I prefer the colour as the background as well. Hugo?

**Comment by FWeinb** [comment]
:+1: for color as background

**Comment by ben-eb** [comment]
Done. Added mixin support as well.

screen shot 2015-01-01 at 14 50 24

**Comment by HugoGiraudel** [comment]
I need to review and merge this when I get time.

**Comment by ben-eb** [comment]
No rush. :smile:

**Comment by HugoGiraudel** [comment]
@ben-eb Sorry to ask you this mate. Branches should be headed to `develop`. Would you care do it perhaps?

**Comment by ben-eb** [comment]
OK if I close this and open a new PR?

**Comment by HugoGiraudel** [comment]
Totally.

**Pull request closed without merging**
