### PR TITLE
Don't default to writing a sourcemap

### PR DESCRIPTION
**Pull request by samgiles**
This causes errors when using the theme's CSS directly as the source map is not included in the package as a dependency.

This PR might not fit with your workflow so feel free to alter, but it would be good to see the source map URL not included in the default distribution.

Sam

### CODE REVIEW

**Comment by HugoGiraudel** [comment]
Ping @SassDoc/owners.

**Comment by pascalduez** [comment]
All good for removing the source map from the package.
As for the `sass-dev` task, I'm not sure we need it. But we can tweak that later.

**Comment by valeriangalliat** [comment]
Fine for me. :+1:

**Comment by HugoGiraudel** [comment]
Okay, then we can merge and release. @pascalduez, feel like you can do it?

**Comment by pascalduez** [comment]
`+ sassdoc-theme-default@2.3.2`

**Pull request merged**
