### PR TITLE
[RFR] Add Open Graph tags

### PR DESCRIPTION
**Pull request by eduardoboucas**
Also deleted indentation on conditional blocks

### CODE REVIEW

**Comment by HugoGiraudel** [comment]
@SassDoc/owners All good?

**Comment by valeriangalliat** [comment]
Yep.

**Comment by HugoGiraudel** [comment]
Thanks @eduardoboucas!

**Comment by eduardoboucas** [comment]
My pleasure. :)

**Comment by HugoGiraudel** [comment]
Although I don't know when this will be live. Either we push a patch at some point, else it will wait for SassDoc 2.1.

**Pull request merged**
