### PR TITLE
group description

### PR DESCRIPTION
**Pull request by xi**
See https://github.com/SassDoc/sassdoc/issues/520
Depends on https://github.com/SassDoc/sassdoc/pull/534 and https://github.com/SassDoc/sassdoc-extras/pull/39

### CODE REVIEW

**Comment by pascalduez** [comment]
This would need a bit more space at the bottom, right now if feels strained.

Screenshot from 2019-03-10 16-56-49

**Comment by xi** [comment]
Is there alteady some CSS that would fit or should I create a new class?

**Comment by pascalduez** [comment]
> Is there alteady some CSS that would fit or should I create a new class?

@xi Sorry for the lag... I don't see any class that would fit, so please create a new one.

**Comment by xi** [comment]
done

**Pull request merged**
