### PR TITLE
[RFR] Change Google Analytics code to Universal Analytics

### PR DESCRIPTION
**Pull request by eduardoboucas**
Update Google Analytics code to use [Universal Analytics](https://support.google.com/analytics/answer/2790010?hl=en-GB). It's the most recent tracking code from Google and is the one provided when a new Analytics account is created.

### CODE REVIEW

**Comment by HugoGiraudel** [comment]
@SassDoc/owners All good?

**Comment by pascalduez** [comment]
:+1:

**Comment by HugoGiraudel** [comment]
Any chance you could keep only the first commit so I could merge this?

**Comment by eduardoboucas** [comment]
Done. Sorry for the mess!

**Comment by HugoGiraudel** [comment]
@SassDoc/owners Should we merge this on `develop` rather than `master`?

**Comment by valeriangalliat** [comment]
On `develop`, yep.

**Comment by HugoGiraudel** [comment]
@eduardoboucas Any chance you could submit this PR on `develop` please?

**Comment by eduardoboucas** [comment]
Done [here](https://github.com/SassDoc/sassdoc-theme-default/pull/63).

**Pull request closed without merging**
