### PR TITLE
[RFR] Added logo to footer and changed big flat tint areas

### PR DESCRIPTION
**Pull request by HugoGiraudel**

### CODE REVIEW

**Comment by kaelig** [comment]
Thanks a lot for shipping this in time for v2!

Now the FTLabs team and I feel that we'd really love a less "bulky" header, something more subtle. If there's a plan to rework this area let us know, otherwise we'll just create our own theme (but we really liked the old default theme, so it'd be a shame).

**Comment by HugoGiraudel** [comment]
Do you have some fix in mind that I could merge perhaps?

**Comment by kaelig** [comment]
Sure! You seem to like purple, how about we make the text and the background slightly tinted (instead of being a pure grey)?

See below, all colors come from a variation of `rgba(92, 72, 99, 0.x)` (equivalent of #5C4863):

screenshot 2015-02-03 23 09 59

Not sure contrasts are high enough, it's hard to judge with the monitor I'm using right now.

Would that be on brand?

**Comment by HugoGiraudel** [comment]
I like it.

**Comment by HugoGiraudel** [comment]
Do you feel like you could PR on `develop`?

**Comment by FWeinb** [comment]
@kaelig That looks awesome!

**Comment by HugoGiraudel** [comment]
Done with [https://github.com/SassDoc/sassdoc-theme-default/commit/a6c745bc506d48cb6053567667b649a7fe845721](https://github.com/SassDoc/sassdoc-theme-default/commit/a6c745bc506d48cb6053567667b649a7fe845721).

**Comment by kaelig** [comment]
Merci !

**Pull request merged**
