### PR TITLE
Fix #86 invalid anchors

### LINKED ISSUE #86: Search suggestions hrefs are no longer valid
Since PR #84 modified the markup of each section to include the group in the `id` attribute, this change breaks the search suggestions feature, since generated anchors are no longer valid.

One way to solve this could be to modify [this file](https://github.com/SassDoc/sassdoc-theme-default/blob/master/assets/js/search.js):
```` javascript
  Search.prototype.initialize = function () {
    // Fuse engine instanciation
    this.index = new Fuse($.map($(this.conf.search.items), function (item) {
      var $item = $(item);

      return {
        group: $item.data('group'), // <=== To include group
        name: $item.data('name'),
        type: $item.data('type'),
        node: $item
      };
    }), this.conf.fuse);

    this.initializeSearch();
  };
````

And here:

```` javascript
  Search.prototype.fillSuggestions = function (items) {
    var searchSuggestions = $(this.conf.search.suggestionsWrapper);
    searchSuggestions.html('');
 
    var suggestions = $.map(items.slice(0, 10), function (item) {
      var $li = $('<li />', {
        'data-group': item.group,
        'data-type': item.type,
        'data-name': item.name,
        'html': '<a href="#' + item.group + '-' + item.type + '-' + item.name + '"><code>' + item.type.slice(0, 3) + '</code> ' + item.name + '</a>'
      });

      searchSuggestions.append($li);
      return $li;
    });

    return suggestions;
  };
````

And add this new data-group attribute to each `.sassdoc__item` [here](https://github.com/SassDoc/sassdoc-theme-default/blob/master/views/includes/partials/sidebar.html.swig#L35):
```` html
<li class="sidebar__item  sassdoc__item" data-group="{{ group_name }}" data-name="{{ item.context.name }}" data-type="{{ item.context.type }}">
````

### PR DESCRIPTION
**Pull request by ricardocasares**
Fixes #86

### CODE REVIEW

**Comment by HugoGiraudel** [comment]
Looks good. @SassDoc/owners?

**Comment by valeriangalliat** [comment]
Sweet. :guitar:

**Comment by pascalduez** [comment]
Looks got to me at the code level, untested though.

**Comment by pascalduez** [comment]
Refs SassDoc/sassdoc#448

**Pull request merged**
