### PR TITLE
[RFR] Include font antialiased for mac

### PR DESCRIPTION
**Pull request by dbeff**
I'm testing the sass docs and I am really enjoying using . But I missed these properties in default theme css to improve font rendering in Mac browsers like firefox and chrome . So I decided to include here . Congratulations for the great work !

```
-webkit-font-smoothing: antialiased;
-moz-osx-font-smoothing: grayscale;
```

### CODE REVIEW

**Comment by valeriangalliat** [comment]
Hello,

Why don't you put this in a Stylish stylesheet for all websites (or even at browser/system level if possible)? I believe that's how you'll enjoy best font rendering for *your* setup and tastes, for *all* websites.

**Comment by pascalduez** [comment]
Hey,

those properties are to be used cautiously, they often do more harm than good.

- They shouldn't be used on the `body` but more targeting specific items.
- They may be used to improve problematic edge cases, like poorly hinted fonts, small font-sizes, white text on black, and such.  

For `sassdoc-theme-default` I haven't noticed any issues, particularly on Mac.

**Comment by dbeff** [comment]
In fact is not a problem, just a better way to display the source. I tested and in my opinion was a little better.

**Comment by dbeff** [comment]
Exemple with antialiased
exemple

**Comment by pascalduez** [comment]
I understand you feeling, I had the same dilemma on several projects.
Sadly those properties are not granular enough IMO.
It's either too much or too few. But the too much part is really linked to OSX.

**Comment by valeriangalliat** [comment]
I maintain this is relevant only as system-wide configuration and have nothing to do as a per-website optimisation (and I don't like having to fix OSX defaults in every single website).

I manage my font rendering at the system level and the font in *all* websites looks fabulous to me (but I believe font rendering is a personal preference and should remain an user configuration).

So I encourage you to configure your system font rendering according to your tastes, so that you'll enjoy it in a much broader context!

Unless @HugoGiraudel or @FWeinb want to add something, I'm in favor of closing this PR.

**Comment by HugoGiraudel** [comment]
I'd rather not implement something like this. I think Valérian is right in saying that this should be done as a browser/system wide configuration rather than from within a stylesheet.

**Comment by dbeff** [comment]
Hi guys, i believe that particular site properties improved the visibility of the font. Open Sans works great with these properties but this really is just my opinion . And as I said congratulations for the project , very well designed and very easy to use. Thanks!

**Comment by HugoGiraudel** [comment]
Hey @dbeff. Thank you very much for the pull request, however we will not merge it. In case some other persons come to say those CSS declarations should be added, we'll consider adding them.

Hope you do not mind.

**Pull request closed without merging**
