### PR TITLE
Use `descriptionPath` filter

### PR DESCRIPTION
**Pull request by pascalduez**
- Refs #66 
- Refs SassDoc/sassdoc-extras#18

### CODE REVIEW

**Comment by pascalduez** [comment]
@HugoGiraudel `sassdoc-extras` 2.3.0 published, please check whether the current description integration suits you.

The thing is, since generated markdown will most likely contains tags (heading, paragraphs,...) they will inherit user agent defaults. Not sure if we should reset or let it as is.

**Comment by HugoGiraudel** [comment]
> The thing is, since generated markdown will most likely contains tags (heading, paragraphs,...) they will inherit user agent defaults. Not sure if we should reset or let it as is.

I think I'll do a little something about this.

**Comment by HugoGiraudel** [comment]
Please review my commit. :)

**Comment by pascalduez** [comment]
I'm not sure about the fact that if no description is given it should fallback to package.description ?
Or at least the "description" title seems redundant and eat space

Those titles are too massive IMO.

screen shot 2015-02-16 at 18 47 01
screen shot 2015-02-16 at 18 48 53
screen shot 2015-02-16 at 18 47 26

**Comment by HugoGiraudel** [comment]
What do you suggest?

**Comment by pascalduez** [comment]
* Don't put an "introduction" title.
* Reduce a bit the font-size of those titles.

I just run a quick test and marked leave inline styles and `<style>` blocks untouched, which means users could have some control over that description.
<sub><sup>Comic-sans red for instance</sup></sub>

**Comment by HugoGiraudel** [comment]
Done. All good?

**Comment by pascalduez** [comment]
Wow, great !

**Comment by HugoGiraudel** [comment]
@pascalduez Then you can merge. :)

**Comment by pascalduez** [comment]
Thanks @HugoGiraudel !

**Pull request merged**
